#!/usr/bin/env bash
sleep ${RANDOM:0:2}s
cd ~
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
FILE=.enable-auto-git-pull
if [ -f "$FILE" ]; then
   if grep -q $GIT_BRANCH "$FILE"; then
      exec &>> ~/site/cron-auto-git-pull-repo.log.txt
      date
      git fetch --quiet
      git pull
   fi
fi
