#!/usr/bin/env python3
import argparse
import datetime
import json
import os
import socket
import subprocess

import git
import psutil
from dotenv import load_dotenv
from OpenSSL import crypto as c
from requests import get, put
from requests.api import put
from statusnotifications import *

parser = argparse.ArgumentParser(description='EE status report')
parser.add_argument('--output', default=True, action=argparse.BooleanOptionalAction, dest='output',
                    help='print report')
parser.add_argument('--generate-report', default=False, action=argparse.BooleanOptionalAction, dest='generatereport',
                    help='generate report for http access')
parser.add_argument('--send-report', default=False, action=argparse.BooleanOptionalAction, dest='sendreport',
                    help='send report to medelexis')
args = parser.parse_args()

eeConfig = load_dotenv("${INSTALL_DIR}/.env")
site_status = {}

SITE_UUID = os.environ.get('X_EE_SITE_UUID') or "missing-uuid"

# site
site_status["site-uuid"] = SITE_UUID
site_status["report-time"] = datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S.%f%z')

# system
system = {}
site_status["system"] = system

system['fqdn'] = socket.getfqdn()

boot_time = datetime.datetime.fromtimestamp(psutil.boot_time())
system['boot-time'] = boot_time.strftime('%Y-%m-%dT%H:%M:%S.%f%z')
system['uname'] = " ".join(os.uname())

# determine installation time via /lost+found
if os.path.isdir('/lost+found'):
    lost_and_found = os.stat('/lost+found')
    lost_and_found_ctime_dt = datetime.datetime.fromtimestamp(lost_and_found.st_ctime)
    system['installation-time'] = lost_and_found_ctime_dt.strftime('%Y-%m-%dT%H:%M:%S.%f%z')

# system.network
network = {}
system['network'] = network

external_ip = get('https://tools.medelexis.ch/myip').text
network['external-ip'] = external_ip

# system.disk
disk = {}
system['disk'] = disk

for partition in psutil.disk_partitions():
    diskUsage = {}
    disk[partition.mountpoint] = diskUsage
    _diskUsage = psutil.disk_usage(partition.mountpoint)
    diskUsage['total'] = _diskUsage.total
    diskUsage['used'] = _diskUsage.used
    diskUsage['free'] = _diskUsage.free
    diskUsage['percent'] = _diskUsage.percent

# ee
ee = {}
site_status['ee'] = ee

repo = git.Repo(os.environ.get('INSTALL_DIR'))
git = {}
ee['git'] = git
git['branch'] = repo.active_branch.name
git['branch-head-commit'] = str(repo.head.commit)
# git fetch regularily done via cron
git['origin-branch-head-commit'] = str(repo.rev_parse('origin/'+repo.active_branch.name))

# ee.config
config = {}
ee['config'] = config

config['hostname'] = os.environ.get('EE_HOSTNAME')
config['organisation-name'] = os.environ.get('ORGANISATION_NAME')
config['mis-project-id'] = os.environ.get('MIS_PROJECTID')
config['host-internal-ip'] = os.environ.get('EE_HOST_INTERNAL_IP')
config['enable-bookstack'] = os.environ.get('ENABLE_BOOKSTACK')
config['enable-elexis-rcp'] = os.environ.get('ENABLE_ELEXIS_RCP')
config['enable-elexis-server'] = os.environ.get('ENABLE_ELEXIS_SERVER')
config['enable-nextcloud'] = os.environ.get('ENABLE_NEXTCLOUD')
config['enable-ocrmypdf'] = os.environ.get('ENABLE_OCRMYPDF')
config['enable-rocketchat'] = os.environ.get('ENABLE_ROCKETCHAT')
config['enable-solr'] = os.environ.get('ENABLE_SOLR')

# ee.site
site = {}
ee['site'] = site

# file does not exist on fresh installation
try:
    certfile = open(os.environ.get('SITE_DIR')+"/certificate.crt", "rb")
    cert = c.load_certificate(c.FILETYPE_PEM, certfile.read())
    cert_not_after = datetime.datetime.strptime(
        cert.get_notAfter().decode('ascii'), '%Y%m%d%H%M%SZ')
    site['cert-not-after'] = cert_not_after.strftime('%Y-%m-%dT%H:%M:%S.%f%z')
    certfile.close
except:
    site['cert-not-after'] = "error reading file"


checkNotifications(site_status)

# perform output

if args.output:
    json_dump = json.dumps(site_status, indent=2)
    print(json_dump)

if args.generatereport:
    with open(os.environ.get('SITE_DIR')+'/status.json', 'w') as f:
        json.dump(site_status, f, indent=2)

if args.sendreport:
    put_url = "https://ee.medelexis.ch/reports/" + SITE_UUID+".json"
    put(put_url, json=site_status)
