#!/usr/bin/env bash
${INSTALL_DIR}ee system cmd stop
${INSTALL_DIR}ee system cmd rm -f elexis-web-api elexis-web-api-nginx elexis-web-api_php
docker volume rm -f elexis-environment_elexis-web-api_php
