# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
  - docker pull mysql:8
  - docker pull medevit/eenv-config
  - patch -p0 docker/compose/rocketchat.yml < .test/rocketchat_trust_localhost.patch

after_script:
  - ./ee system cmd logs --no-color > ee-docker-logs.txt
  - ./ee system cmd stop
  - ./ee system cmd rm -f
  - docker volume prune -f
  - docker stop test-mysql-8
  - ./ee setup clean
  - rm .env

stages:
  - testCore
  - testFull

#
# Elexis-Environment core only: ldap, keycloak, web, elexis-server
#
core: 
  stage: testCore
  script:
    - cp .test/.env.core .env # copy test environment configuration
    - source .env 
    - ./ee setup mysql_init_code > .test/mysql/a_init.sql # prepare mysql init code for mysql startup
    - docker run --name test-mysql-8 --rm -e MYSQL_ROOT_PASSWORD=test-pw -v $PWD/.test/mysql/:/docker-entrypoint-initdb.d/:ro -p 33306:3306 -d mysql:8
    - ./ee system cmd pull -q # while mysql starts up pull required images
    - sleep 15 # wait for mysql - lame solution
    - ./ee setup configure # prepare setup and generate self-signed-cert next
    - openssl req -x509 -newkey rsa:2048 -keyout ./site/certificate.key -out ./site/certificate.crt -days 365 -nodes -subj "/CN=localhost"
    - ./ee system cmd up -d --build # start the elexis-environment
    - .test/wait_for_http_200_es.sh # wait for elexis-server to become ready
    - ./ee system cmd ps # print the status of the elexis-environment containers
    - docker wait elexis-environment_ee-config_1 # wait for the elexis-server-config to exit
    - ./ee system runtest # run the core runtest
    - ./ee setup sync_users_es_keycloak # sync users from ES to keycloak
  artifacts:
    when: on_failure
    paths:
      - ee-docker-logs.txt

#
# Elexis-Environment all-modules-enabled
#
full:
  stage: testFull
  script:
    - cp .test/.env.full .env
    - source .env
    - ./ee setup mysql_init_code > .test/mysql/a_init.sql # prepare mysql init code for mysql startup
    - docker run --name test-mysql-8 --rm -e MYSQL_ROOT_PASSWORD=test-pw -v $PWD/.test/mysql/:/docker-entrypoint-initdb.d/:ro -p 33306:3306 -d mysql:8
    - ./ee system cmd pull -q # while mysql starts up
    - sleep 15 # wait for mysql - lame solution
    - ./ee setup configure # prepare setup and generate self-signed-cert next
    - openssl req -x509 -newkey rsa:2048 -keyout ./site/certificate.key -out ./site/certificate.crt -days 365 -nodes -subj "/CN=localhost"
    - ./ee system cmd up -d --build
    - .test/wait_for_http_200_rocketchat.sh
    - ./ee system cmd ps
    - docker wait elexis-environment_ee-config_1
    - ./ee system runtest
  artifacts:
    when: on_failure
    paths:
      - ee-docker-logs.txt
      - "*.png"