#!/usr/bin/env bash

APP_DIR=`pwd`
RELEASE_REPOSITORY=''

if [[ ! -f "$APP_DIR/BCLFile" ]]; then
    exit 0
fi

RELEASE_REPOSITORY=`head -n 1 $APP_DIR/BCLFile`

if [[ ! -d "$APP_DIR/cli" ]]; then
    mkdir -p $APP_DIR/cli
fi

for PACKAGE_BUILD in `tail -n+2 $APP_DIR/BCLFile`; do
    if [[ -d .$PACKAGE_BUILD ]]; then
        rm -rf .$PACKAGE_BUILD
    fi
    PACKAGE_NAME=`echo $PACKAGE_BUILD | awk '{split($0,a,/-v[0-9]+\.[0-9]+\.[0-9]+-/); print a[1]}'`

    if [[ -d "$APP_DIR/cli/$PACKAGE_NAME" && -f "$APP_DIR/cli/$PACKAGE_NAME/BUILD" ]]; then
        INSTALLED_PACKAGE=`head -n 1 $APP_DIR/cli/$PACKAGE_NAME/BUILD`
        if [ $PACKAGE_BUILD == $INSTALLED_PACKAGE  ]; then
            echo $PACKAGE_BUILD already installed
            continue
        fi
    fi
    echo Installing $PACKAGE_BUILD...
    git clone -b $PACKAGE_BUILD $RELEASE_REPOSITORY --depth 1 .$PACKAGE_BUILD
    cp -R  .$PACKAGE_BUILD/* $APP_DIR/cli
    rm -rf .$PACKAGE_BUILD
done
