#!/usr/bin/env bash

if [ $# == 0 ]; then
    exit 3
fi

APP_DIR=`pwd`
PACKAGE_NAME="${!#}"
PACKAGE_RELEASE_TAG=''
RELEASE_REPOSITORY=''
EXECUTABLE_SUFFIX='ctl'
TMP_DIR="$HOME/.bcltmp"

if [[ ! -d "$APP_DIR/$PACKAGE_NAME" ]]; then
    >&2 echo -e "\033[31mProject '$PACKAGE_NAME' not found\033[39m"
    exit 3
fi

if [[ -f "$APP_DIR/$PACKAGE_NAME/BUILD" ]]; then
    PACKAGE_RELEASE_TAG=`head -n 1 $APP_DIR/$PACKAGE_NAME/BUILD`
    RELEASE_REPOSITORY=`tail -n 1 $APP_DIR/$PACKAGE_NAME/BUILD`
fi

if [[ -d "$TMP_DIR" ]]; then
    >&2 echo -e "\033[31mThe $TMP_DIR already exists\033[39m"
    >&2 echo "Please check if you have another build publishing or remove the directory."
    exit 3
fi

git clone $RELEASE_REPOSITORY --depth 1 $TMP_DIR
cd $TMP_DIR
git update-ref -d HEAD
git checkout -b $PACKAGE_RELEASE_TAG
rm -rf $TMP_DIR/*
cp $APP_DIR/$PACKAGE_NAME$EXECUTABLE_SUFFIX $TMP_DIR
cp -R $APP_DIR/$PACKAGE_NAME $TMP_DIR
git add -A
git commit -m "Publishing $PACKAGE_RELEASE_TAG"
git push $RELEASE_REPOSITORY $PACKAGE_RELEASE_TAG
rm -rf $TMP_DIR
