#!/usr/bin/env bash
export T="### [BACKUP]"
DATE=$(date +"%d%m%Y_%H%M%S")
BACKUPDIR=${SITE_DIR}backup/$DATE/

function sepline {
    echo "#####################################################################################"
}

sepline
echo "# $DATE Elexis-Environment Backup"
sepline
echo "## Checking EE runstate ..."

IFS=$'\n'
CONTAINER_STATUS=$(docker ps -a --filter label=com.docker.compose.project=elexis-environment --format "{{.ID}} \"{{.Status}}\" {{.Names}}")
for container in $CONTAINER_STATUS
do
    if [[ $container == *"\"Up "* ]]; then
        echo "!!!! RUNNING CONTAINER: $container"
        echo "!!!! A container is still running, you have to stop all containers before executing this script."
        echo "!!!! Exiting."
        exit 0
    fi
done

echo "## Fetching updated docker backup tool ..."
docker pull -q loomchild/volume-backup

$(mkdir -p ${BACKUPDIR})
sepline
echo "## Start Backup to ${BACKUPDIR}"
sepline

# write backup metainfo
cat << EOF > ${BACKUPDIR}ee-backup.info
ELEXIS-ENVIRONMENT-BACKUP
date:        $(date)
hostname:    $(hostname -f)
ee git rev:  $(cd ${INSTALL_DIR}; git log -1 --oneline)
installdir:  ${INSTALL_DIR}


EOF
docker version >> ${BACKUPDIR}ee-backup.info

#
# .env file
#
echo "$T .env file => "
FILENAME=${BACKUPDIR}env
cp ${INSTALL_DIR}.env ${FILENAME}

#
# /site data
# 
FILENAME=${BACKUPDIR}site_files.tar
echo "$T /site files => $FILENAME"
echo $SITE_DIR
tar -C ${SITE_DIR} -cvf $FILENAME --exclude='./backup/' .

#
# named volumes
#
VOLUMES=$(docker volume ls --filter label=com.docker.compose.project=elexis-environment --format "{{.Name}}")

for volume in $VOLUMES
do
    FILENAME=${BACKUPDIR}NV_${volume}.tar.bz2
    echo "$T named volume $volume => $FILENAME"
    docker run -v $volume:/volume --rm loomchild/volume-backup backup - > ${FILENAME}
done

#
# tar to single file
#
FILENAME=${SITE_DIR}backup/ee-backup_${DATE}.tar
echo "## Create backup file $FILENAME"
tar -C ${BACKUPDIR} -cvf ${FILENAME} .

echo "## Removing backup dir $BACKUPDIR"
rm -Rf ${BACKUPDIR}

sepline 
echo "### FINISHED - file is $FILENAME"
echo "### !!!!! SQL Databases are NOT part of this backup !!!!! "
echo "### !!!!!         you have to take care of this     !!!!! "
sepline

