#!/usr/bin/env bash
export T="### [BACKUP]"
DATE=$(date +"%d%m%Y_%H%M%S")
BACKUPDIR=${SITE_DIR}backup/$DATE/

THISDIR=$(cd `dirname $0` && pwd)
source $THISDIR/common.sh

sepline
echo "# $DATE Elexis-Environment Backup"
sepline

assert_docker_stopped
fetch_current_backup_tool

$(mkdir -p ${BACKUPDIR})
sepline
echo "## Start Backup to ${BACKUPDIR}"
sepline

# write backup metainfo
cat << EOF > ${BACKUPDIR}ee-backup.info
ELEXIS-ENVIRONMENT-BACKUP
date:          $(date)
hostname:      $(hostname -f)
ee git branch: R1
ee git rev:    $(cd ${INSTALL_DIR}; git log -1 --oneline)
installdir:    ${INSTALL_DIR}


EOF
docker version >> ${BACKUPDIR}ee-backup.info

#
# .env file
#
FILENAME=${BACKUPDIR}env
echo "$T .env file => $FILENAME"
cp ${INSTALL_DIR}.env ${FILENAME}

#
# /site data
# 
FILENAME=${BACKUPDIR}site_files.tar
echo "$T /site files => $FILENAME"
tar -C ${SITE_DIR} -cf $FILENAME --exclude './.gitignore' --exclude './README.md' --exclude='./backup/' .

#
# named volumes
#
VOLUMES=$(docker volume ls --filter label=com.docker.compose.project=elexis-environment --format "{{.Name}}")

for VOLUME in $VOLUMES
do
    FILENAME=${BACKUPDIR}NV_${VOLUME}.tar.bz2
    echo "$T named volume $VOLUME => $FILENAME"
    docker run -v $VOLUME:/volume --rm loomchild/volume-backup backup - > ${FILENAME}
done

#
# tar to single file
#
FILENAME=${SITE_DIR}backup/ee-backup_${DATE}.tar
echo "## Create ee-backup file $FILENAME"
tar -C ${BACKUPDIR} -cf ${FILENAME} .

echo "## Removing backup dir $BACKUPDIR"
rm -Rf ${BACKUPDIR}

sepline 
echo "### FINISHED - file is $FILENAME"
echo "### !!!!! SQL Databases are NOT part of this backup !!!!! "
echo "### !!!!!         you have to take care of this     !!!!! "
sepline

