#!/usr/bin/env bash
DOCKER_DIR=${INSTALL_DIR}/docker/compose/

params=()
params+=(-f ${DOCKER_DIR}/web.yml)
params+=(-f ${DOCKER_DIR}/postgres.yml)
params+=(-f ${DOCKER_DIR}/keycloak.yml)
params+=(-f ${DOCKER_DIR}/ee-config.yml)

[[ $ENABLE_ELEXIS_SERVER == true ]] && params+=(-f ${DOCKER_DIR}/elexis-server.yml)
[[ $ENABLE_MYELEXIS_SERVER == true ]] && params+=(-f ${DOCKER_DIR}/myelexis-server.yml)
[[ $ENABLE_BOOKSTACK == true ]] && params+=(-f ${DOCKER_DIR}/bookstack.yml)
[[ $ENABLE_NEXTCLOUD == true ]] && params+=(-f ${DOCKER_DIR}/nextcloud.yml)
[[ $ENABLE_SAMBA == true ]] && params+=(-f ${DOCKER_DIR}/samba.yml)
[[ $ENABLE_SOLR == true ]] && params+=(-f ${DOCKER_DIR}/solr.yml)
[[ $ENABLE_OCRMYPDF == true ]] && params+=(-f ${DOCKER_DIR}/ocrmypdf.yml)
[[ $ENABLE_ELEXIS_WEB == true ]] && params+=(-f ${DOCKER_DIR}/elexis-web.yml)
[[ $ENABLE_GUACAMOLE == true ]] && params+=(-f ${DOCKER_DIR}/guacamole.yml)
[[ $ENABLE_MATRIX == true ]] && params+=(-f ${DOCKER_DIR}/matrix.yml)

# allow overrides of default values for specific installations (e.g. development)
if [ -e ${INSTALL_DIR}/.env.override ]
then
    #echo "Using ${INSTALL_DIR}/.env.override"
    docker compose -p elexis-environment --env-file ${INSTALL_DIR}/.env.override ${params[@]} "$@"
else
    docker compose -p elexis-environment ${params[@]} "$@"
fi
