#!/usr/bin/env bash


function {{ function_name }}() {
    local root_dir;
    local project_name={{ project_name }};
    root_dir=`dirname "$(perl -e 'use Cwd "abs_path"; print abs_path(shift)' "$(which ${COMP_WORDS[0]})")"`
    root_dir="$root_dir/$project_name"

    local curr_arg;
    curr_arg="${COMP_WORDS[COMP_CWORD]}"
    prev_arg="${COMP_WORDS[COMP_CWORD-1]}"

    # Locate the correct command to execute by looking through the app directory
    # for folders and files which match the arguments provided on the command line.
    local cmd_file="$root_dir/app/"
    local cmd_arg_start=1

    # If current or previous argument is "help", don't suggest anyting
    if [[ "$curr_arg" == "help" || "$prev_arg" == "help" ]]; then
        COMPREPLY=()
        return
    fi

    while [[ -d "$cmd_file" && $cmd_arg_start -le $COMP_CWORD ]]; do
        cmd_file="$cmd_file/${COMP_WORDS[cmd_arg_start]}"
        cmd_arg_start=$(($cmd_arg_start+1))
    done

    # If we've found something which doesn't exist, then let's
    # look at its containing directory for info.
    if [[ ! -e "$cmd_file" ]]; then
        cmd_file=`dirname $cmd_file`
    fi

    # If we found a command, then suggest the `--help` argument
    # TODO: Add parsing of .usage files for this
    if [[ -f "$cmd_file" ]]; then
        # Check if we've already got a `--help`, don't output anything
        # if we do.
        for i in `seq $cmd_arg_start $COMP_CWORD`; do
            if [[ "${COMP_WORDS[$i]}" == "--help" ]]; then
                COMPREPLY=()
                return
            fi
        done

        COMPREPLY=(`compgen -W '--help' -- "$curr_arg"`)
    # If we found a directory, then show all the commands which are
    # available within it, as well as the `help` virtual command.
    elif [ -d "$cmd_file" ]; then
        local opts=("help")
        local file_list=(`find $cmd_file/ -maxdepth 1 ! -path $cmd_file/ ! -iname '*.*' -print`)

        for file in "${file_list[@]}"; do
            opts=("${opts[@]}" `basename $file`)
        done

        IFS="
        "
        COMPREPLY=(`compgen -W "$(printf '%s\n' "${opts[@]}")" -- "$curr_arg"`)
    fi
}
