#!/bin/sh
# Inspired by https://github.com/sebastl/wireguard-docker/blob/stretch/run
set -eu

if [ ! -f /etc/wireguard/private-key ]; then
    echo "$(date): Generating keypair" >&2
    umask 077
    wg genkey >/etc/wireguard/private-key
fi

echo "$(date): Prepare iptables" >&2
WEB_IP=$(getent hosts web | cut -d' ' -f1)
iptables -F
iptables -A POSTROUTING -t nat -j MASQUERADE

# to forward ssh port to host system
HOST_IP=$(ip route show 0.0.0.0/0 | cut -d\  -f3)

PRIVATE_KEY=$(cat /etc/wireguard/private-key)
PUBLIC_KEY=$(cat /etc/wireguard/private-key | wg pubkey)
echo $PUBLIC_KEY > /site/pubkey.txt
chmod ugo+r /site/pubkey.txt
echo "Public Key: ${PUBLIC_KEY}"

# generate /etc/wireguard/wg0.conf
echo "$(date): Generating /etc/wireguard/wg0.conf" >&2
echo "[Interface]" >/etc/wireguard/wg0.conf
echo "Address = ${WG_CLIENT_IP}" >>/etc/wireguard/wg0.conf
echo "PrivateKey = ${PRIVATE_KEY}" >>/etc/wireguard/wg0.conf
echo "PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A PREROUTING -i %i -s ${WG_CLIENT_IP} -p tcp --dport 8443 -j DNAT --to-destination ${WEB_IP}:8443; iptables -t nat -A PREROUTING -i %i -s ${WG_CLIENT_IP} -p tcp --dport 22 -j DNAT --to-destination ${HOST_IP}:22" >>/etc/wireguard/wg0.conf
echo "[Peer]" >>/etc/wireguard/wg0.conf
echo "Endpoint = ${WG_SERVER_ENDPOINT}" >>/etc/wireguard/wg0.conf
echo "PublicKey = ${WG_SERVER_PUBKEY}" >>/etc/wireguard/wg0.conf
echo "PresharedKey = ${WG_SERVER_PRESHAREDKEY}" >>/etc/wireguard/wg0.conf
echo "AllowedIPs = 0.0.0.0/0" >>/etc/wireguard/wg0.conf
echo "PersistentKeepalive = 25" >>/etc/wireguard/wg0.conf

echo "$(date): Starting Wireguard wg0"
wg-quick up wg0

# TODO document registration of client in wikijs.medelexis.ch
# https://hub.docker.com/r/cmulk/wireguard-docker
# https://prismplex.com/de/blog/wireguard-server-docker
# https://www.linode.com/docs/networking/vpn/set-up-wireguard-vpn-on-ubuntu/

sleep infinity &
wait $!
