#!/bin/sh
# On restart, the web container may change its ip.
# We need to update the iptables rule to catch this
while true; do
    sleep 30

    WEB_IP=$(getent hosts web | cut -d' ' -f1)
    if [ -z "${WEB_IP// }" ]; then
        continue
    fi

    iptables -R PREROUTING 1 -t nat -i wg0 -p tcp --dport 8443 -j DNAT --to-destination ${WEB_IP}:8443
    iptables -R PREROUTING 2 -t nat -i wg0 -p tcp --dport 443 -j DNAT --to-destination ${WEB_IP}:8444
done
