#!/bin/bash
#
# Echoes the substituted SQL commands for creating the required databases and users
#

source ../.env

echo "CREATE DATABASE $RDBMS_ELEXIS_DATABASE;"
echo "CREATE USER $RDBMS_ELEXIS_USERNAME@'172.%' IDENTIFIED BY '$RDBMS_ELEXIS_PASSWORD';"
echo "GRANT ALL PRIVILEGES ON $RDBMS_ELEXIS_DATABASE.* TO '$RDBMS_ELEXIS_USERNAME'@'172.%';"
echo "CREATE DATABASE $RDBMS_BOOKSTACK_DATABASE;"
echo "CREATE USER $RDBMS_BOOKSTACK_USERNAME@'172.%' IDENTIFIED BY '$RDBMS_BOOKSTACK_PASSWORD';"
echo "GRANT ALL PRIVILEGES ON $RDBMS_BOOKSTACK_DATABASE.* TO $RDBMS_BOOKSTACK_USERNAME@'172.%';"
echo "FLUSH PRIVILEGES;"