#!/bin/bash
T="[ELEXIS-DB] "
echo "$T $(date)"

echo "$T Setting EE_HOSTNAME in elexis rdbms config table to [${EE_HOSTNAME}]"
LASTUPDATE=$(date +%s)000
SQL_STRING="DELETE FROM CONFIG WHERE param = 'EE_HOSTNAME'; INSERT INTO CONFIG(lastupdate, param, wert) VALUES ('${LASTUPDATE}','EE_HOSTNAME', '${EE_HOSTNAME}');"
USQL_PARAM="${RDBMS_ELEXIS_TYPE-$RDBMS_TYPE}://${RDBMS_ELEXIS_USERNAME}:${RDBMS_ELEXIS_PASSWORD}@${RDBMS_ELEXIS_HOST-$RDBMS_HOST}:${RDBMS_ELEXIS_PORT-$RDBMS_PORT}/${RDBMS_ELEXIS_DATABASE}"
/usql -t $USQL_PARAM -c "$SQL_STRING"