#!/usr/bin/env bash
if [ "$1" == "json" ]; then 
    ${INSTALL_DIR}ee system cmd -f ${DOCKER_DIR}/wireguard.yml exec wireguard wg-json
else
    ${INSTALL_DIR}ee system cmd -f ${DOCKER_DIR}/wireguard.yml exec wireguard wg
fi