#!/usr/bin/env bash

if [ $# == 0 ]; then
    exit 3
fi

export LDAPTLS_REQCERT=never

DN="${!#}"
ldapdelete -H ldaps://$EE_HOSTNAME -D cn=$ADMIN_USERNAME,$ORGANISATION_BASE_DN -w $ADMIN_PASSWORD -x -s $password $DN