#!/usr/bin/env bash

if [ $# == 0 ]; then
    exit 3
fi

export LDAPTLS_REQCERT=never

DN="${!#}"
read -p "Enter new password: " password
read -p "Validate: " password2

if [ $password != $password2 ]; then
    echo "Passwords are not equal"
    exit -1
fi

echo Setting password for $DN...

ldappasswd -H ldaps://$EE_HOSTNAME -D cn=$ADMIN_USERNAME,$ORGANISATION_BASE_DN -w $ADMIN_PASSWORD -x -s $password "cn=$DN,ou=people,$ORGANISATION_BASE_DN"