services:
  postgres:
    image: docker.io/postgres:16-alpine
    volumes:
      - postgres_pgdata:/var/lib/postgresql/data
      - ./assets/postgres/:/assets/:ro
    networks:
      - backend
    mem_limit: 1G
    memswap_limit: 1G
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 5s
      start_interval: 2s
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}

volumes:
    postgres_pgdata: