version: '3'

services:
    wireguard:
        build: ../wireguard
        restart: unless-stopped
        volumes:
            - wireguard_conf:/etc/wireguard
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        networks:
            - myelexis_bridge
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        environment:
            - WG_SERVER_ENDPOINT=${WG_SERVER_ENDPOINT-bridge.myelexis.ch:51820}
            - WG_DISABLE_SSH_MANHOLE=${WG_DISABLE_SSH_MANHOLE-false}
            - EE_HOSTNAME
            - MIS_APIKEY
            - MIS_PROJECTID


# healthcheck
volumes:
    wireguard_conf:

networks:
    myelexis_bridge: