#!/usr/bin/env bash

# Is EE_TOOLS_CERTBOT_SHARED_SECRET set?
if [[ "$EE_TOOLS_CERTBOT_SHARED_SECRET" =~ ^optional_not_set$ ]]; then
    echo -e -e "\033[36mABORT\033[39m: EE_TOOLS_CERTBOT_SHARED_SECRET variable is not set."
    exit -1
fi

# Is Hostname *.myelexis.ch
if [[ ! "$EE_HOSTNAME" =~ ^.*\.myelexis.ch$ ]]; then
    echo -e -e "\033[36mABORT\033[39m: Hostname is $EE_HOSTNAME, this script works for hostnames *.myelexis.ch only."
    exit -1
fi

export EXOSCALE_API_KEY=$(echo $EE_TOOLS_CERTBOT_SHARED_SECRET | cut -f1 -d:)
export EXOSCALE_API_SECRET=$(echo $EE_TOOLS_CERTBOT_SHARED_SECRET | cut -f2 -d:)

# run | renew
function run-goacme-lego {
    docker run --rm --name lego -v "${SITE_DIR}goacme-lego:/goacme-lego" -e EXOSCALE_API_KEY -e EXOSCALE_API_SECRET goacme/lego \
        --email sysadmin-ee@medelexis.ch --accept-tos --dns exoscale --domains ${EE_HOSTNAME} \
        --dns.resolvers 1.1.1.1 --dns.resolvers 8.8.8.8 \
        --path /goacme-lego $1
}

# TODO test X_EE_CERTBOT_SHARED_SECRET
mkdir -p ${SITE_DIR}goacme-lego
echo "=============================================================================================="
echo "Creating/Refreshing cert for ${EE_HOSTNAME}... this can take up to 2 minutes!"
echo "=============================================================================================="

docker pull goacme/lego
CERTFILE=${SITE_DIR}goacme-lego/certificates/$EE_HOSTNAME.crt

if [ -f "$CERTFILE" ]; 
then
    echo "Existing cert found, calling renew ..."
    run-goacme-lego renew
else
    echo "No existing cert found, calling run ..."
    run-goacme-lego run
fi

if [ ! -f $CERTFILE ]; then
    echo -e -e "\033[36mABORT\033[39m: No generated certificate found, not installing symlinks"
    exit -1
fi

# cert is now available in ${SITE_DIR}goacme-lego/certificates/
# if files exist, and are not symlinks to our cert, back them up
FILE=${SITE_DIR}certificate.crt
[ -f $FILE ] && [ ! -L $FILE ] && mv -v $FILE $FILE.bkup
ln -sf $CERTFILE $FILE

FILE=${SITE_DIR}certificate.key
[ -f $FILE ] && [ ! -L $FILE ] && mv -v $FILE $FILE.bkup
ln -sf ${SITE_DIR}goacme-lego/certificates/$EE_HOSTNAME.key $FILE

echo "=> Remember to restart web container to pick-up cert changes"
