#!/usr/bin/env bash
set -x
docker build -t ee-configure ${INSTALL_DIR}docker/ee-config/.
PWD=$(pwd)
docker run --rm --env-file ${INSTALL_DIR}.env -v $PWD/assets/:/assets -it ee-configure
docker rmi ee-configure
