#!/usr/bin/env bash
# Reset all users passwords
# https://www.keycloak.org/docs/latest/server_admin/#resetting-a-user-s-password

source ../stage_ee_start_setup/keycloak_functions.sh
echo "$T $(date)"

$KCADM config credentials --server https://$EE_HOSTNAME/keycloak/auth  --realm master --user KeycloakAdmin --client admin-cli --password $ADMIN_PASSWORD

echo "$T Resetting all user passwords ... "
USER_LIST=$($KCADM get users -r ElexisEnvironment --format csv --fields id,username --noquotes)
for USER_ENTRY in $USER_LIST
do
        USER_ID=$(echo $USER_ENTRY | cut -d"," -f1)
        USER_NAME=$(echo $USER_ENTRY | cut -d"," -f2)
        echo "$T user $USER_NAME"
        $KCADM update users/$USER_ID/reset-password -r ElexisEnvironment -s type=password -s value=changeme -s temporary=true -n
done

echo "$T =============== ACHTUNG ==============="
echo "$T  UNBEDINGT Passwörter von Administrator"
echo "$T     Accounts ODER Accounts OHNE OTP    "
echo "$T             SOFORT NEU SETZEN          "
echo "$T =============== ACHTUNG ==============="