#!/usr/bin/env bash
# Synchronize users from Elexis-Server to Keycloak

SQL_STRING="SELECT U.ID,U.KONTAKT_ID,K.BEZEICHNUNG1,K.BEZEICHNUNG2,K.BEZEICHNUNG3,K.EMAIL from USER_ AS U INNER JOIN KONTAKT AS K ON U.KONTAKT_ID=K.ID"
USQL_PARAM="${RDBMS_ELEXIS_TYPE-$RDBMS_TYPE}://${RDBMS_ELEXIS_USERNAME}:${RDBMS_ELEXIS_PASSWORD}@${RDBMS_ELEXIS_HOST-$RDBMS_HOST}:${RDBMS_ELEXIS_PORT-$RDBMS_PORT}/${RDBMS_ELEXIS_DATABASE}"
/usql --set SHOW_HOST_INFORMATION=false --field-separator="|" -C $USQL_PARAM -c "$SQL_STRING" -o ./users.csv
if [[ $? -ne 0 ]]
then
  echo Error exporting users. Exiting.
  exit 1 
fi

sed -i '/^$/d' ./users.csv
cat ./users.csv

java -jar /ee-bin/keycloak/util/KeycloakUtil.jar -l KeycloakAdmin -t -v -p $ADMIN_PASSWORD -u https://$EE_HOSTNAME/keycloak/auth -c syncUsersFromElexisCsv -f ./users.csv